name: "✨ 功能建议"
description: "提交一个功能优化或新功能建议"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！请尽量详细描述你的想法，这将帮助我们更好地理解你的需求。

  - type: dropdown
    id: type
    attributes:
      label: 建议类型
      options:
        - 新功能
        - 功能优化
        - UI/UX 改进
        - 性能优化
        - 其他
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 请清晰地描述你期望的功能或改进
      placeholder: "描述你希望添加或改进的功能..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 使用场景
      description: 请描述这个功能会在什么场景下使用，解决什么问题
      placeholder: "例如：当我使用 XX 功能时，我希望能够..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 你是否考虑过其他替代方案？
      placeholder: "描述你考虑过的其他解决方案..."
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: 确认事项
      options:
        - label: 我已经检查过是否有相同的功能请求
          required: true
